### ISSUE TITLE
Allow a user to view and create workspaces in the PMR

### ISSUE THREAD

**Issue by dbrnz** [opencor/opencor#969]
Adding this as a tracker item -- see https://docs.google.com/document/d/16m12yxQxwI10EZPTRnNvXV4xcF54XFQqZz3a4LiujI0/edit?ts=56c2f305 for background.

**Comment by dbrnz** [comment]
This, IMHO, is now ready for feedback, with new snapshots of my [pmrworkspace](https://github.com/dbrnz/opencor/tree/pmrworkspace) branch available for [OS/X](http://www.bcs.co.nz/downloads/OpenCOR-2016-08-03-OSX.zip) and [Windows](http://www.bcs.co.nz/downloads/OpenCOR-2016-08-03-Windows.exe).

Issues to discuss and/or do include:

1.  **Fork v's clone**. Should the terminolgy on PMR and in OpenCOR distinguish between `clone` and `fork` operations? Your comments please @nickerso.
     * `clone` can be applied to any workspace to create a local copy.
     * `fork` can be applied to another user's workspace to create our copy of it, before locally cloning.
     * If OpenCOR has a local clone of another user's workspace then forking it would create our fork on OpenCOR and push the local copy.
     * As part of an exposure view PMR has _"To begin collaborating on this work, please use your git client and issue this command"_ and describes using `git clone`. Should there also be an option to fork into "My Workspaces"??

2.  Use a QTimer to periodically refresh the status of a workspace as well as updating its status whenever any file in the workspace is created/modified by OpenCOR.
    * To minimise polling overhead we could keep all workspaces closed except the "current" one. Would an OpenCOR user want to have multiple workspaces open??
    * We could minimise screen updates by only only refreshing the screen if there has been an actual change in status.
   * Issue #1028 can be closed -- a workspace may contain other files than those created/edited by OpenCOR and so we cannot rely upon OpenCOR's notifications to signal modifications to a workspace. 

3.  At workspace commit time we need to get the user's name and email. Should this come from OpenCOR/Preferences?? Or from PMR?? (are they available from the Web API?). Or from git's global configuration settings on the local PC??

4.  Implement `pull` when the workspace on PMR is ahead of the local copy. What about merge conflicts? We also cannot `push` until remote changes have been pulled (so need to show a dimmed `push` icon).

4.  A cloned workspace might have changes/commits but can't be pushed because we don't own it. Again we need to show a dimmed `push` icon (or maybe one with a diagonal red line through it?).

6.  Implement "Show containing folder" for Linux/Ubuntu. What is the default file manager bundled with Ubuntu? Should we allow a user to change it, say under OpenCOR/PMRWorkspaces/Preferences??

7.  Show the files that will be committed when inputting a commit message, along with username/email git will use.

8.  Implement a context menu for files and folders in a workspace tree view??

**Comment by nickerso** [comment]
First, just to note that at least the OS X snapshot didn't really work for me. I can log in and see my workspaces, but cloning resulted in either an OpenCOR crash (although the actual clone was made on disk, but not visible when relaunching OpenCOR) or an apparently successful clone being created but not displayed in the GUI. Refreshing the listing would then trigger the contents of the cloned workspace to be visible.

I could make changes and stage them and commit them, but pushing just seemed to hang for ages and required a force quit of OpenCOR to stop it - without the changes making it to PMR.

1. PMR does have a `fork` available to users in the workspace view, whereas that collaborate on the exposure pages is really aimed at encouraging users to clone the workspace rather than simply download the files. I don't think at this stage that OpenCOR should worry about forking vs cloning, the user should always be working with their workspaces and if they want to fork someone else's workspace they can use the web interface for that.

2. the notifications shown in the workspace view when files have been changed are useful, obviously good to achieve that in a way with the least overhead :)

3. I'd vote for an OpenCOR setting/preference. Users may want to use different identities with different tools.

4. In attempting to avoid scaring the user, I'd vote for a simple "synchronise" button, and then behind the scenes that would do any pulling and/or pushing that is required to get the cloned workspace and the remote working in the same state. If this would result in any merges, conflicts, or other user action being required, then for now I would simply propagate that to a nicely informative message to the user pointing them to the appropriate documentation for sorting it out using standard Git tools.

5. A nice graphic highlighting to the user that they can't send a workspace back to PMR would be very useful. Even better if it links to documentation explaining to the user how they can fork and synchronise their local clone with the remote workspace (or ask the owner for write access).

7. +1

8. might be useful, but perhaps not essential.

**Comment by agarny** [comment]
I am currently on holiday, so I don't currently have time to test your branch, but will do on my return (on 15 August). Otherwise, @nickerso's replies look sound to me. Just a few notes:

2) FWIW, OpenCOR's file manager uses a `QTimer` to check whether opened files (or files in the `File Organiser` window) have changed. It does that check every second. It also now does so only when OpenCOR is active (see issue #1048).

3) Hmm... yet another argument in favour of working on issue #193.

6) I take it that your "Show containing folder" feature is implemented on Windows and OS X? If so, how did you do it? I mean, a cross platform solution to implementing your feature should be a simple call to `QDesktopServices::openUrl(QUrl::fromLocalFile(myFolderPath))`?

**Comment by dbrnz** [comment]
Issues raised from the above comments:

- [ ] #1055 OpenCOR crashes after cloning a workspace.
- [ ] #1056 Use a QTimer to periodically refresh the status of a workspace.
- [ ] #1057 Allow the user's name and email to be set in Preferences.
- [ ] #1058 Replace `pull` and `push` by a `synchronise` operation.
- [ ] #1059 Write and link to documentation describing git workflow in OpenCOR.
- [ ] #1060 Simplify code to "Show containing folder".
- [ ] #1061 Show the files that will be committed when inputting a commit message.
- [ ] #1062 Cannot push commits to PMR?

**Comment by agarny** [comment]
Thanks for creating/working on all those issues @dbrnz. Just one (very) minor thing: you will have seen that I have very slightly renamed your issues by prepending "PMR Workspace window:" to them (and removing the final full point). The idea is that we can, at a glance, see what the focus of the issue is.

**Comment by dbrnz** [comment]
I've released new snapshots of my [pmrworkspace](https://github.com/dbrnz/opencor/tree/pmrworkspace) branch for [OS/X](http://www.bcs.co.nz/downloads/OpenCOR-2016-08-13-OSX.zip) and [Windows](http://www.bcs.co.nz/downloads/OpenCOR-2016-08-13-Windows.exe). This snapshot:
* Fixes the crash after cloning, #1055.
* Periodically updates the displayed workspace display, #1056.
* Has simplified code to show the containing folder, #1060 .
* Shows the files to be committed in the commit message, #1061.
* Implements workspace synchronisation with PMR, #1058. (Although suitable user messages need to provided when a merge results in a conflict).

**Comment by dbrnz** [comment]
The snapshots from yesterday had problems with synchronising a newly created workspace. This has been fixed in new snapshots for [OS/X](http://www.bcs.co.nz/downloads/OpenCOR-2016-08-14-OSX.zip) and [Windows](http://www.bcs.co.nz/downloads/OpenCOR-2016-08-13-Windows.exe).

**Comment by agarny** [comment]
This has effectively been done (see issues #1124 and #1141), so closing.
